### ISSUE TITLE
suggestion install using go

### ISSUE THREAD

**Issue by Sy3Omda** [SolomonSklash/chomp-scan#59]
https://github.com/SolomonSklash/chomp-scan/blob/05263b5cf3b7f33b13bb02cd887f57edee5d49c6/installer.sh#L139

why we just install aquatone using go command `go get github.com/michenriksen/aquatone`
to get the latest aquatone version without editing in the `installer.sh` every new release

**Comment by SolomonSklash** [comment]
I just looked into this. I honestly didn't know it was an option. However, I tested it and I don't believe using `go get` gets the latest version. The Go version doesn't seem to respect the `-version` flag, so I can't tell if it is current. Ideally I would use `go get` for every tool that supported it, but in this case I think it's better to manually update the version. This is partly because from the user end, they have to run `./installer.sh` to update either way. Also, aquatone has had some major breaking changes lately, and I would like to make sure I know if I am introducing bugs when I update it.

I appreciate the feedback!
